<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.hms</groupId>
        <artifactId>home-media-server</artifactId>
        <version>0.1.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>media-stream-service</artifactId>
    <name>media-stream-service</name>

    <properties>
        <libtorrent4j.version>2.1.0-39</libtorrent4j.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.hms</groupId>
            <artifactId>shared-lib</artifactId>
        </dependency>

        <dependency>
            <groupId>com.hms</groupId>
            <artifactId>sql-lib</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-kafka</artifactId>
        </dependency>

        <!-- Source: https://mvnrepository.com/artifact/org.xerial/sqlite-jdbc -->
        <dependency>
            <groupId>org.xerial</groupId>
            <artifactId>sqlite-jdbc</artifactId>
            <version>3.53.1.0</version>
            <scope>compile</scope>
        </dependency>

        <!-- Source: https://mvnrepository.com/artifact/com.google.guava/guava -->
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>33.6.0-jre</version>
            <scope>compile</scope>
        </dependency>

        <!-- Source: https://mvnrepository.com/artifact/com.frostwire/jlibtorrent -->
        <dependency>
            <groupId>com.frostwire</groupId>
            <artifactId>jlibtorrent</artifactId>
            <version>1.2.0.18</version>
            <scope>compile</scope>
        </dependency>

        <!-- Source: https://mvnrepository.com/artifact/com.frostwire/jlibtorrent-linux -->
        <dependency>
            <groupId>com.frostwire</groupId>
            <artifactId>jlibtorrent-linux</artifactId>
            <version>1.2.0.18</version>
            <scope>compile</scope>
        </dependency>

        <!-- <dependency>
            <groupId>com.frostwire</groupId>
            <artifactId>jlibtorrent-windows</artifactId>
            <version>1.2.0.18</version>
            <scope>compile</scope>
        </dependency> -->
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>