server:
  port: 8081

spring:
  application:
    name: media-catalog-service
  
  kafka:
    bootstrap-servers: kafka:9092
    # consumer:
    #   group-id: media-catalog-service
    #   auto-offset-reset: earliest
    #   key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #   value-deserializer: com.hms.shared.messaging.mediaupdates.MediaUpdateDeserializer
    # producer:
    #   key-serializer: org.apache.kafka.common.serialization.StringSerializer
    #   value-serializer: com.hms.shared.messaging.mediaupdates.MediaUpdateSerializer
