server:
    port: 8082

spring:
    ai:
        google:            
            genai:
                api-key: ${GEMINI_AI_API_KEY}
                chat:                    
                    model: gemini-2.5-flash
        model:
            chat: google-genai
    application:
        name: media-acquisition-service
    kafka:
        bootstrap-servers: kafka:9092
