server:
  port: ${MEDIA_STREAM_SERVICE_PORT:8083}

spring:
  application:
    name: media-stream-service
  servlet:
    multipart:
      max-file-size: ${STREAM_MAX_FILE_SIZE:10GB}
      max-request-size: ${STREAM_MAX_REQUEST_SIZE:10GB}
      file-size-threshold: 2MB
  

  kafka:
    bootstrap-servers: kafka:${KAFKA_PORT:9092}

