server:
  port: 8083

spring:
  application:
    name: media-stream-service
    
  docker:
    compose:
      lifecycle-management: start_and_stop
      start:
        command: up
      stop:
        command: down
        timeout: 10s    
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: media-stream-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
