server:
  port: 8083

spring:
  application:
    name: media-stream-service
  servlet:
    multipart:
      max-file-size: ${STREAM_MAX_FILE_SIZE:10GB}
      max-request-size: ${STREAM_MAX_REQUEST_SIZE:10GB}
      file-size-threshold: 2MB
  

  kafka:
    bootstrap-servers: kafka:9092    
    # consumer:
    #   group-id: media-stream-service
    #   auto-offset-reset: earliest
    #   key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #   value-deserializer: com.hms.shared.messaging.mediaupdates.MediaUpdateDeserializer
    # producer:      
    #   key-serializer: org.apache.kafka.common.serialization.StringSerializer
    #   value-serializer: com.hms.shared.messaging.mediaupdates.MediaUpdateSerializer

